name: keep_money

description: Expense tracker for people.

publish_to: "none"

version: 1.0.1+12

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  animate_do: ^3.0.2
  another_flushbar: ^1.12.29
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  equatable: ^2.0.5
  fading_edge_scrollview: ^2.0.1
  fimber: ^0.6.6
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.9
  flutter_svg_provider: ^1.0.7
  get_it: ^7.2.0
  graphql: ^5.1.1
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  internet_connection_checker: ^0.0.1+4
  intl: ^0.18.0
  path_provider: ^2.0.11
  rxdart: ^0.27.5
  shared_preferences: ^2.0.15
  shimmer: ^2.0.0
  sizer: ^2.0.15

dev_dependencies:
  build_runner: ^2.1.11
  flutter_launcher_icons: ^0.10.0
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  hive_generator: ^1.1.3
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/dev/icon.png"

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/dev/
    - assets/icons/
    - assets/icons/avatars/
    - assets/images/
    - assets/icons/transaction_types/

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/fonts/montserrat/Montserrat-Regular.ttf
        - asset: assets/fonts/montserrat/Montserrat-Bold.ttf
          weight: 700

    - family: Hind Madurai
      fonts:
        - asset: assets/fonts/hind_madurai/HindMadurai-Regular.ttf
        - asset: assets/fonts/hind_madurai/HindMadurai-Bold.ttf
          weight: 700
